elasticsearch_version: 0.20.4
elasticsearch_data_dir: <%=rubber_env.mount_directory%>/elasticsearch/data
elasticsearch_work_dir: <%=rubber_env.mount_directory%>/elasticsearch/work
elasticsearch_log_dir: <%=rubber_env.mount_directory%>/elasticsearch/logs
elasticsearch_http_port: 9200

roles:
  elasticsearch:
    packages: [openjdk-7-jdk, unzip]

web_tools_proxies:
  elasticsearch:
    role: elasticsearch
    port: "#{elasticsearch_http_port}"
    path: /_plugin/head/
